// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Update.Mapper;

#nullable disable

namespace Update.Mapper.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20241115151506_ss")]
    partial class ss
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Update.Mapper.Model.Referans", b =>
                {
                    b.Property<Guid?>("deneme")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("kod")
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid?>("tenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("tipId")
                        .HasColumnType("int");

                    b.HasIndex("tenantId", "kod", "tipId")
                        .IsUnique()
                        .HasFilter("[tenantId] IS NOT NULL AND [kod] IS NOT NULL");

                    b.ToTable("Referans");
                });
#pragma warning restore 612, 618
        }
    }
}
