name: Build and Push Docker Image

on:
  push:
    branches:
      - dev  # veya istediğiniz branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Kodu Checkout Et
        uses: actions/checkout@v3

      - name: Docker Setup
        uses: docker/setup-buildx-action@v2

      - name: Docker Hub Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.hkbn }}
          password: ${{ secrets.Cimbom.1905 }}

      - name: Build and Push Docker Image
        run: |
          docker build -t hkbn/update.mapper:latest .
          docker push hkbn/update.mapper:latest
